### ISSUE TITLE
Button für Wechseln der Wahlergebnisse

### ISSUE THREAD

**Issue by tabea22** [safiscet/SE-DBS-15-16#12]
Button für Wahl 2009 und 2013 auf allen Seiten mit Statistiken (Q...) zum Wechseln zwischen den Wahlen

**Comment by safiscet** [comment]
Funktioniert jetzt überall, ich hab aber noch kein besseres Design hinbekommen oder dass die bisherigen Ids wieder geladen werden, etc.

**Comment by safiscet** [comment]
In Q3 und Q7 wird wieder die ID vom aktuellen Wahlkreis in die URL gepackt (seit b65f335).
In Q6 ergibt das nicht viel Sinn, da die Partei nicht unbedingt in beiden Jahren angetreten ist.
