### ISSUE TITLE
Beschreibung zum Setup unseres Systems

### ISSUE THREAD

**Issue by tabea22** [safiscet/SE-DBS-15-16#17]
Kurze Beschreibung über Daten laden, Dependencies, etc. für die Abgabe am Montag

**Comment by safiscet** [comment]
erste Version fertig, die Dependencies der Webseite und sonstige Libs müssten noch irgendwo aufgenommen werden

**Comment by safiscet** [comment]
Dependencies sind jetzt mit drin
