### ISSUE TITLE
Beschreibung der Besonderheiten unseres Systems

### ISSUE THREAD

**Issue by tabea22** [safiscet/SE-DBS-15-16#18]
Kurze Übersicht über die Besonderheiten eures Systems (wie ihr sie eurem Kunden präsentieren würdet)

**Comment by tabea22** [comment]
- Analysen Q1-Q7 in akzeptabler Zeit darstellen
- Koalitionsdiagramm
- Auswahl des Jahres der Wahl in jeder Analyse möglich
- Farbige Visualisierung zum besseren Verständnis/Überblick

**Comment by safiscet** [comment]
- zu Koalitionsdiagramm: alle Kombinationen von bis zu 3 Parteien, die gesamt mehr als die Hälfte der Sitze besitzen
- komfortable Stimmabgabe
- Easter-Eggs :)

**Comment by tabea22** [comment]
Done
